FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install the dependencies
RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0 && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt

# Copy the GUI application code
COPY app ./app

# Set the entry point for the GUI application
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8002"]