FROM golang:1.20 AS builder

WORKDIR /app

COPY go.mod ./
ENV GOPROXY=https://proxy.golang.org,direct
RUN go mod download

COPY . ./
RUN go build -o vieteduchain ./cmd/main.go

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/vieteduchain .

CMD ["./vieteduchain"]